// data.js
const QUESTIONS = [
     {question:"What is the opposite of 'big'?", options:["small", "slow", "cold"], correct:0},
  {question:"Which one is a fruit?", options:["apple","car","dog"], correct:0},
  {question:"Which word means 'teacher'?", options:["teacher","cat","bus"], correct:0},
  {question:"What color is the sky?", options:["blue","red","black"], correct:0},
  {question:"Which one is a pet?", options:["dog","car","bus"], correct:0},
  {question:"What do you drink?", options:["water","shoe","pencil"], correct:0},
  {question:"Which one is a vehicle?", options:["bike","banana","cat"], correct:0},
  {question:"Which word means 'fast'?", options:["quick","slow","cold"], correct:0},
  {question:"What is the opposite of 'hot'?", options:["cold","warm","tiny"], correct:0},
  {question:"Which one is a sport?", options:["football","apple","pencil"], correct:0},

  {question:"Which one is a fruit?", options:["banana","train","dog"], correct:0},
  {question:"What do you use to write?", options:["pen","orange","milk"], correct:0},
  {question:"Which animal can fly?", options:["bird","dog","fish"], correct:0},
  {question:"Which one is food?", options:["rice","bike","shirt"], correct:0},
  {question:"Which one is a job?", options:["teacher","milk","banana"], correct:0},
  {question:"Which word means 'happy'?", options:["glad","sad","angry"], correct:0},
  {question:"Which one is a drink?", options:["juice","cat","bus"], correct:0},
  {question:"What is the opposite of 'slow'?", options:["fast","small","red"], correct:0},
  {question:"Which is a season?", options:["summer","apple","car"], correct:0},
  {question:"Which one is a place?", options:["school","banana","dog"], correct:0},

  {question:"Which one is a day of the week?", options:["Monday","Banana","Water"], correct:0},
  {question:"Which one is a month?", options:["January","Apple","Milk"], correct:0},
  {question:"Which one is a fruit?", options:["grape","bus","shoe"], correct:0},
  {question:"Which word means 'run'?", options:["run","sleep","sit"], correct:0},
  {question:"Which animal lives in water?", options:["fish","cat","bird"], correct:0},
  {question:"Which one is a building?", options:["library","juice","dog"], correct:0},
  {question:"Which one is a drink?", options:["milk","book","pencil"], correct:0},
  {question:"What is the opposite of 'young'?", options:["old","fast","hot"], correct:0},
  {question:"Which is a school subject?", options:["math","bread","bike"], correct:0},
  {question:"Which one is a vehicle?", options:["bus","apple","dog"], correct:0},

  {question:"Which one is a fruit?", options:["orange","car","shoe"], correct:0},
  {question:"Which word means 'sleep'?", options:["sleep","run","talk"], correct:0},
  {question:"Which one is a job?", options:["student","milk","shirt"], correct:0},
  {question:"Which animal is small?", options:["cat","train","bus"], correct:0},
  {question:"Which one is food?", options:["bread","bike","stone"], correct:0},
  {question:"Which is a feeling?", options:["sad","table","bus"], correct:0},
  {question:"Which word means 'eat'?", options:["eat","run","jump"], correct:0},
  {question:"Which one is a drink?", options:["water","shoe","banana"], correct:0},
  {question:"Which one is a color?", options:["red","bus","dog"], correct:0},
  {question:"What is the opposite of 'dark'?", options:["light","cold","big"], correct:0},

  {question:"Which one is a fruit?", options:["pineapple","pen","cup"], correct:0},
  {question:"Which one is an animal?", options:["dog","car","shirt"], correct:0},
  {question:"Which word means 'write'?", options:["write","jump","swim"], correct:0},
  {question:"Which one is a place?", options:["market","banana","shoe"], correct:0},
  {question:"Which one is food?", options:["noodle","bike","bag"], correct:0},
  {question:"Which word means 'speak'?", options:["speak","run","sleep"], correct:0},
  {question:"Which one is a drink?", options:["juice","bus","cat"], correct:0},
  {question:"Which animal can swim?", options:["fish","cat","bird"], correct:0},
  {question:"Which one is a job?", options:["teacher","water","shirt"], correct:0},
  {question:"Which is a day of the week?", options:["Friday","Orange","Milk"], correct:0},

  {question:"Which is a month?", options:["May","Cat","Bike"], correct:0},
  {question:"Which one is a fruit?", options:["apple","pen","car"], correct:0},
  {question:"Which word means 'read'?", options:["read","eat","jump"], correct:0},
  {question:"Which one is an emotion?", options:["angry","bus","stone"], correct:0},
  {question:"Which one is food?", options:["rice","train","shirt"], correct:0},
  {question:"Which one is a drink?", options:["milk","dog","box"], correct:0},
  {question:"Which is a vehicle?", options:["car","bread","apple"], correct:0},
  {question:"Which one is a place?", options:["school","banana","milk"], correct:0},
  {question:"Which animal is big?", options:["elephant","ant","fish"], correct:0},
  {question:"Which is a color?", options:["blue","cat","bus"], correct:0},

  {question:"Which one is a fruit?", options:["banana","door","shoe"], correct:0},
  {question:"Which one is a job?", options:["student","juice","table"], correct:0},
  {question:"Which word means 'jump'?", options:["jump","read","drink"], correct:0},
  {question:"Which one is food?", options:["bread","car","glass"], correct:0},
  {question:"Which one is a drink?", options:["water","pen","hat"], correct:0},
  {question:"Which is a feeling?", options:["happy","bike","train"], correct:0},
  {question:"Which is a day?", options:["Sunday","Banana","Milk"], correct:0},
  {question:"Which one is a vehicle?", options:["bike","cat","pencil"], correct:0},
  {question:"Which one is a month?", options:["June","Shoe","Dog"], correct:0},
  {question:"Which one is a fruit?", options:["grape","bus","bag"], correct:0},

  {question:"Which one is a place?", options:["library","juice","pencil"], correct:0},
  {question:"Which one is an animal?", options:["bird","car","milk"], correct:0},
  {question:"Which one is food?", options:["noodle","bag","shoe"], correct:0},
  {question:"Which is a subject?", options:["English","Dog","Car"], correct:0},
  {question:"Which one is a drink?", options:["juice","stone","bus"], correct:0},
  {question:"Which one is a job?", options:["teacher","apple","water"], correct:0},
  {question:"Which word means 'walk'?", options:["walk","jump","swim"], correct:0},
  {question:"Which one is a color?", options:["green","fish","bus"], correct:0},
  {question:"Which animal is small?", options:["ant","bus","plane"], correct:0},
  {question:"Which one is food?", options:["rice","car","shoe"], correct:0},

    {question:"Which one is a vegetable?", options:["carrot","car","cat"], correct:0},
  {question:"What do you use to cut paper?", options:["scissors","phone","soap"], correct:0},
  {question:"Which is a fruit?", options:["grape","chair","shoe"], correct:0},
  {question:"Which one is a farm animal?", options:["cow","bus","pen"], correct:0},
  {question:"Which one can fly?", options:["airplane","book","desk"], correct:0},
  {question:"Which one is cold?", options:["ice","fire","sun"], correct:0},
  {question:"Which one grows on trees?", options:["apple","rock","car"], correct:0},
  {question:"What do you wear on your feet?", options:["shoes","gloves","hat"], correct:0},
  {question:"Which is a body part?", options:["hand","table","door"], correct:0},
  {question:"Which one tells time?", options:["clock","pen","bottle"], correct:0},

  {question:"Which one is a color?", options:["yellow","bread","phone"], correct:0},
  {question:"Which one is a sport?", options:["tennis","book","cup"], correct:0},
  {question:"Which one is a season?", options:["winter","pencil","shirt"], correct:0},
  {question:"What do you drink in the morning?", options:["milk","car","shoe"], correct:0},
  {question:"Which one is a musical instrument?", options:["piano","apple","bus"], correct:0},
  {question:"Which word means 'begin'?", options:["start","end","stop"], correct:0},
  {question:"Which one is a farm product?", options:["egg","phone","chair"], correct:0},
  {question:"Which one is a tool?", options:["hammer","banana","dog"], correct:0},
  {question:"Which one is hot?", options:["sun","water","cake"], correct:0},
  {question:"Which one is a vehicle?", options:["train","pen","rice"], correct:0},

  {question:"Which one is an occupation?", options:["doctor","tree","river"], correct:0},
  {question:"What do you write with?", options:["pencil","plate","shoe"], correct:0},
  {question:"Which one is a planet?", options:["Earth","book","banana"], correct:0},
  {question:"Which one is a kitchen item?", options:["spoon","car","hat"], correct:0},
  {question:"Which is a natural resource?", options:["water","phone","table"], correct:0},
  {question:"Which one is delicious to eat?", options:["cake","stone","cup"], correct:0},
  {question:"Which one is a hobby?", options:["painting","river","mountain"], correct:0},
  {question:"Which one is a healthy drink?", options:["water","cola","oil"], correct:0},
  {question:"Which one is a place to buy food?", options:["market","school","station"], correct:0},
  {question:"Which one is a weather condition?", options:["rain","lamp","chair"], correct:0},

  {question:"Which one is a vehicle that moves on water?", options:["ship","bicycle","plane"], correct:0},
  {question:"Which one keeps you warm?", options:["coat","glass","pen"], correct:0},
  {question:"Which one helps you see at night?", options:["lamp","pillow","shoe"], correct:0},
  {question:"Which one do you read?", options:["book","rice","car"], correct:0},
  {question:"Which one grows vegetables?", options:["garden","school","hospital"], correct:0},
  {question:"Which one makes bread?", options:["oven","chair","car"], correct:0},
  {question:"Which one is a building for learning?", options:["school","factory","park"], correct:0},
  {question:"Which one is used to cut food?", options:["knife","shampoo","chair"], correct:0},
  {question:"Which one gives us milk?", options:["cow","dog","fish"], correct:0},
  {question:"Which one lives in a house and barks?", options:["dog","bird","fish"], correct:0},

  {question:"Which one is a useful liquid?", options:["water","stone","pencil"], correct:0},
  {question:"Which one is a holiday month in summer?", options:["July","November","February"], correct:0},
  {question:"Which one is a tool to write on a board?", options:["marker","spoon","plate"], correct:0},
  {question:"Which one tells news on TV?", options:["anchor","teacher","chef"], correct:0},
  {question:"Which one helps people cross water?", options:["bridge","mountain","tree"], correct:0},
  {question:"Which one is used to clean your teeth?", options:["toothbrush","soap","pen"], correct:0},
  {question:"Which one is a sweet food?", options:["chocolate","salt","pepper"], correct:0},
  {question:"Which one is a place to watch movies?", options:["cinema","gym","library"], correct:0},
  {question:"Which one is a mode of communication?", options:["phone","cup","shoe"], correct:0},
  {question:"Which one can you wear on your head?", options:["hat","book","table"], correct:0},

  {question:"Which one helps you hear?", options:["ear","eye","nose"], correct:0},
  {question:"Which one helps you smell?", options:["nose","hand","foot"], correct:0},
  {question:"Which one is used for cleaning?", options:["soap","pencil","banana"], correct:0},
  {question:"Which one is a type of house?", options:["apartment","car","apple"], correct:0},
  {question:"Which one is a tool for digging?", options:["shovel","fork","knife"], correct:0},
  {question:"Which one is used to call someone?", options:["phone","book","pen"], correct:0},
  {question:"Which one is part of a tree?", options:["leaf","shoe","chair"], correct:0},
  {question:"Which one is used to carry things?", options:["bag","plate","bottle"], correct:0},
  {question:"Which one is a type of weather?", options:["windy","cloudy","apple"], correct:0},
  {question:"Which one is a place to buy books?", options:["bookstore","garage","garden"], correct:0},

  {question:"Which one is a healthy food?", options:["vegetable","candy","chip"], correct:0},
  {question:"Which one is made from wood?", options:["table","glass","rice"], correct:0},
  {question:"Which one is a tool to measure time?", options:["clock","ruler","spoon"], correct:0},
  {question:"Which one is a weekend day?", options:["Saturday","Tuesday","Wednesday"], correct:0},
  {question:"Which one do farmers grow?", options:["rice","phone","shoe"], correct:0},
  {question:"Which one is in the sky at night?", options:["stars","car","tree"], correct:0},
  {question:"Which one keeps you dry in the rain?", options:["umbrella","fan","clock"], correct:0},
  {question:"Which one is used for writing on paper?", options:["pen","plate","shoe"], correct:0},
  {question:"Which one helps you taste food?", options:["tongue","nose","ear"], correct:0},
  {question:"Which one is used for playing soccer?", options:["ball","book","plate"], correct:0},

  {question:"Which one is a piece of furniture?", options:["chair","cloud","apple"], correct:0},
  {question:"Which one is used to open a door?", options:["key","phone","apple"], correct:0},
  {question:"Which one is a tool for cleaning the floor?", options:["broom","knife","fork"], correct:0},
  {question:"Which one is a cold drink?", options:["cola","soup","rice"], correct:0},
  {question:"Which one is made from cotton?", options:["shirt","stone","glass"], correct:0},
  {question:"Which one is for cutting hair?", options:["scissors","fork","spoon"], correct:0},
  {question:"Which one is a place to sleep?", options:["bed","table","chair"], correct:0},
  {question:"Which one is a food you fry?", options:["egg","water","book"], correct:0},
  {question:"Which one gives us eggs?", options:["hen","cow","fish"], correct:0},
  {question:"Which one is in the kitchen?", options:["stove","bed","car"], correct:0},

  {question:"Which one is used to write lessons?", options:["notebook","shoe","phone"], correct:0},
  {question:"Which one helps you walk on snow?", options:["boots","sandals","socks"], correct:0},
  {question:"Which one is used to heat food?", options:["microwave","pen","bottle"], correct:0},
  {question:"Which one is a place for medicine?", options:["clinic","bar","park"], correct:0},
  {question:"Which one is a public transport?", options:["taxi","sofa","lamp"], correct:0},
  {question:"Which one is a musical group member?", options:["singer","teacher","chef"], correct:0},
  {question:"Which one is part of the body that sees?", options:["eye","ear","hand"], correct:0},
  {question:"Which is used for cutting paper?", options:["scissors","fork","knife"], correct:0},
  {question:"Which one grows in the garden?", options:["flower","car","phone"], correct:0},
  {question:"Which one is a quiet place to read?", options:["library","stadium","market"], correct:0},

    {question:"Which one is a wild animal?", options:["tiger","cow","chicken"], correct:0},
  {question:"Which one is used to light a dark room?", options:["lamp","cup","fork"], correct:0},
  {question:"Which one is a fruit you peel?", options:["banana","bread","car"], correct:0},
  {question:"Which one is part of the body?", options:["leg","cup","tree"], correct:0},
  {question:"Which one is used for washing hands?", options:["soap","pencil","towel"], correct:0},
  {question:"Which one protects you from rain?", options:["umbrella","plate","book"], correct:0},
  {question:"Which one is a type of drink?", options:["juice","shoe","chalk"], correct:0},
  {question:"Which one is a school subject?", options:["math","plate","chair"], correct:0},
  {question:"Which one is made of paper?", options:["newspaper","key","water"], correct:0},
  {question:"Which one is a small animal?", options:["mouse","bus","tree"], correct:0},

  {question:"Which one is used to cook soup?", options:["pot","plate","glass"], correct:0},
  {question:"Which one is a place to swim?", options:["pool","school","cinema"], correct:0},
  {question:"Which one is used to see far objects?", options:["binoculars","fork","spoon"], correct:0},
  {question:"Which one is a part of the face?", options:["nose","hand","foot"], correct:0},
  {question:"Which one is a natural place?", options:["forest","building","hotel"], correct:0},
  {question:"Which one can fly in the sky?", options:["bird","lion","tiger"], correct:0},
  {question:"Which one is a type of weather?", options:["sunny","chair","soap"], correct:0},
  {question:"Which one is used for music?", options:["guitar","brush","ruler"], correct:0},
  {question:"Which one is a communication tool?", options:["computer","cup","box"], correct:0},
  {question:"Which one is used to carry students?", options:["school bus","motorbike","plate"], correct:0},

  {question:"Which one is a plant?", options:["flower","dog","car"], correct:0},
  {question:"Which one is used for drinking?", options:["cup","shoe","pen"], correct:0},
  {question:"Which is a type of building?", options:["hospital","banana","pencil"], correct:0},
  {question:"Which one is used to color pictures?", options:["crayons","knife","spoon"], correct:0},
  {question:"Which one has wheels?", options:["bicycle","egg","chair"], correct:0},
  {question:"Which one is a pet?", options:["cat","tiger","cow"], correct:0},
  {question:"Which one is a warm season?", options:["summer","winter","autumn"], correct:0},
  {question:"Which one is used to clean the board?", options:["eraser","fork","glass"], correct:0},
  {question:"Which one is a time of day?", options:["morning","table","car"], correct:0},
  {question:"Which one is for holding plants?", options:["flower pot","fridge","box"], correct:0},

  {question:"Which one is a body joint?", options:["knee","ear","nose"], correct:0},
  {question:"Which one is a tall animal?", options:["giraffe","cat","pig"], correct:0},
  {question:"Which one is used for shopping?", options:["cart","bed","pen"], correct:0},
  {question:"Which one is for boiling water?", options:["kettle","plate","pencil"], correct:0},
  {question:"Which one is sweet?", options:["honey","salt","pepper"], correct:0},
  {question:"Which one protects your eyes?", options:["sunglasses","gloves","boots"], correct:0},
  {question:"Which one is a sea animal?", options:["fish","cow","bird"], correct:0},
  {question:"Which one is a tree part?", options:["branch","shoe","phone"], correct:0},
  {question:"Which one belongs in the bathroom?", options:["shampoo","fork","clock"], correct:0},
  {question:"Which one helps you go upstairs?", options:["stairs","window","desk"], correct:0},

  {question:"Which one is a big body of water?", options:["ocean","cup","bowl"], correct:0},
  {question:"Which one shows temperature?", options:["thermometer","ruler","marker"], correct:0},
  {question:"Which one can you play?", options:["game","rice","car"], correct:0},
  {question:"Which one is a container?", options:["bottle","pencil","shoe"], correct:0},
  {question:"Which one is a mode of travel?", options:["train","cup","hat"], correct:0},
  {question:"Which one is eaten at breakfast?", options:["bread","pencil","soap"], correct:0},
  {question:"Which one is a dessert?", options:["ice cream","water","salt"], correct:0},
  {question:"Which one is a part of the hand?", options:["finger","toe","nose"], correct:0},
  {question:"Which one has pages?", options:["book","shoe","knife"], correct:0},
  {question:"Which one is used for measuring length?", options:["ruler","bowl","brush"], correct:0},

  {question:"Which one is a small insect?", options:["ant","cow","lion"], correct:0},
  {question:"Which one is a home appliance?", options:["fridge","car","tree"], correct:0},
  {question:"Which one is noisy?", options:["drum","pillow","paper"], correct:0},
  {question:"Which one lives in the water?", options:["fish","cat","dog"], correct:0},
  {question:"Which one is eaten as a snack?", options:["chips","soap","pen"], correct:0},
  {question:"Which one is a round object?", options:["ball","book","cupboard"], correct:0},
  {question:"Which one helps you breathe?", options:["lungs","hand","eye"], correct:0},
  {question:"Which one is a thing you wear?", options:["shirt","knife","pencil"], correct:0},
  {question:"Which one is used for cutting?", options:["knife","spoon","cup"], correct:0},
  {question:"Which one is a type of job?", options:["teacher","blanket","window"], correct:0},

  {question:"Which one is used to eat soup?", options:["spoon","knife","stick"], correct:0},
  {question:"Which one has four wheels?", options:["car","dog","chair"], correct:0},
  {question:"Which one is used at school?", options:["chalk","knife","bowl"], correct:0},
  {question:"Which one is a piece of clothing?", options:["jacket","leaf","stone"], correct:0},
  {question:"Which one is part of the mouth?", options:["teeth","hair","ear"], correct:0},
  {question:"Which one is used for timekeeping?", options:["watch","pen","plate"], correct:0},
  {question:"Which one is found in the sky?", options:["cloud","desk","cup"], correct:0},
  {question:"Which one is a public place?", options:["library","pan","shoe"], correct:0},
  {question:"Which one is used for cleaning floors?", options:["mop","knife","glass"], correct:0},
  {question:"Which one is something you drink?", options:["water","rock","key"], correct:0},

  {question:"Which one is a house pet?", options:["dog","lion","wolf"], correct:0},
  {question:"Which one is a container for water?", options:["bucket","plate","shoe"], correct:0},
  {question:"Which one grows in orchards?", options:["fruit","iron","paper"], correct:0},
  {question:"Which one is a cold place?", options:["North Pole","desert","forest"], correct:0},
  {question:"Which one tells directions?", options:["compass","broom","glass"], correct:0},
  {question:"Which one is soft?", options:["pillow","rock","metal"], correct:0},
  {question:"Which one is worn on the hands?", options:["gloves","hat","scarf"], correct:0},
  {question:"Which one is a fast animal?", options:["cheetah","turtle","sheep"], correct:0},
  {question:"Which one is a body part?", options:["shoulder","bottle","cap"], correct:0},
  {question:"Which one is used for cooking?", options:["pan","shoe","pen"], correct:0},

    {question:"Which one is a farm animal?", options:["cow","lion","tiger"], correct:0},
  {question:"Which one is used for writing?", options:["pen","spoon","plate"], correct:0},
  {question:"Which one grows on trees?", options:["apple","car","shoe"], correct:0},
  {question:"Which one can fly?", options:["bird","elephant","dog"], correct:0},
  {question:"Which one is for drinking?", options:["glass","shoe","key"], correct:0},
  {question:"Which one is a kind of weather?", options:["rainy","knife","fork"], correct:0},
  {question:"Which one is a fruit?", options:["orange","hat","rock"], correct:0},
  {question:"Which one is part of the leg?", options:["knee","hair","nose"], correct:0},
  {question:"Which one is hot?", options:["sun","ice","snow"], correct:0},
  {question:"Which one is used for cutting paper?", options:["scissors","candle","cup"], correct:0},

  {question:"Which one is a vehicle?", options:["bus","banana","cat"], correct:0},
  {question:"Which one is cold?", options:["ice","fire","sun"], correct:0},
  {question:"Which one is eaten?", options:["food","pencil","shirt"], correct:0},
  {question:"Which one lives in the jungle?", options:["monkey","cow","goat"], correct:0},
  {question:"Which one is used in class?", options:["notebook","pillow","blanket"], correct:0},
  {question:"Which one is a color?", options:["blue","cup","fish"], correct:0},
  {question:"Which one has leaves?", options:["tree","shoe","cupboard"], correct:0},
  {question:"Which one is used to wash hair?", options:["shampoo","knife","glass"], correct:0},
  {question:"Which one is a sport?", options:["football","cooking","sleeping"], correct:0},
  {question:"Which one is part of the head?", options:["hair","foot","hand"], correct:0},

  {question:"Which one is a meal?", options:["breakfast","pencil","door"], correct:0},
  {question:"Which one is used to draw?", options:["pencil","fork","stick"], correct:0},
  {question:"Which one grows in the garden?", options:["flower","table","hat"], correct:0},
  {question:"Which one is a body part?", options:["neck","plate","bottle"], correct:0},
  {question:"Which one can swim?", options:["fish","cat","tiger"], correct:0},
  {question:"Which one is a holiday month?", options:["December","plate","box"], correct:0},
  {question:"Which one is a natural place?", options:["beach","pencil","bag"], correct:0},
  {question:"Which one is made of metal?", options:["key","banana","bread"], correct:0},
  {question:"Which one is a school item?", options:["ruler","pan","shoe"], correct:0},
  {question:"Which one is used for eating?", options:["fork","ball","ruler"], correct:0},

  {question:"Which one is a drink?", options:["milk","rock","paper"], correct:0},
  {question:"Which one is used at night to sleep?", options:["bed","bus","book"], correct:0},
  {question:"Which one can jump?", options:["frog","fish","chair"], correct:0},
  {question:"Which one is a room in the house?", options:["kitchen","flower","bottle"], correct:0},
  {question:"Which one is worn on the feet?", options:["shoes","hat","gloves"], correct:0},
  {question:"Which one is a kind of animal?", options:["horse","pen","cup"], correct:0},
  {question:"Which one is a type of fruit?", options:["grape","clock","water"], correct:0},
  {question:"Which one is used for music?", options:["piano","plate","bag"], correct:0},
  {question:"Which one is round?", options:["circle","box","paper"], correct:0},
  {question:"Which one grows in the sea?", options:["seaweed","lion","pig"], correct:0},

  {question:"Which one has wheels?", options:["car","cat","tree"], correct:0},
  {question:"Which one is used to sweep the floor?", options:["broom","knife","spoon"], correct:0},
  {question:"Which one is a kind of job?", options:["doctor","cup","milk"], correct:0},
  {question:"Which one is sweet?", options:["cake","salt","pepper"], correct:0},
  {question:"Which one is used to keep food cold?", options:["fridge","table","mirror"], correct:0},
  {question:"Which one has feathers?", options:["bird","dog","fish"], correct:0},
  {question:"Which one produces honey?", options:["bee","cow","duck"], correct:0},
  {question:"Which one is used for drawing?", options:["crayon","cup","fork"], correct:0},
  {question:"Which one is a family member?", options:["mother","glass","pan"], correct:0},
  {question:"Which one tells time?", options:["clock","pen","spoon"], correct:0},

  {question:"Which one is used to paint?", options:["brush","bottle","spoon"], correct:0},
  {question:"Which one can float?", options:["boat","rock","chair"], correct:0},
  {question:"Which one is a school subject?", options:["science","blanket","plate"], correct:0},
  {question:"Which one flies in the sky?", options:["plane","pig","dog"], correct:0},
  {question:"Which one is used for storing books?", options:["bookshelf","pillow","glass"], correct:0},
  {question:"Which one is a common drink?", options:["water","stone","leaf"], correct:0},
  {question:"Which one grows in fields?", options:["rice","car","cup"], correct:0},
  {question:"Which one is used for gardening?", options:["shovel","bowl","pen"], correct:0},
  {question:"Which one shines at night?", options:["moon","cup","chair"], correct:0},
  {question:"Which one is used in winter?", options:["coat","plate","comb"], correct:0},

  {question:"Which one is an electronic device?", options:["phone","ball","pencil"], correct:0},
  {question:"Which one is used in the kitchen?", options:["pan","book","shoe"], correct:0},
  {question:"Which one can bark?", options:["dog","cat","rabbit"], correct:0},
  {question:"Which one is spicy?", options:["chili","sugar","milk"], correct:0},
  {question:"Which one is a bedroom item?", options:["pillow","car","tree"], correct:0},
  {question:"Which one grows on a farm?", options:["corn","radio","plate"], correct:0},
  {question:"Which one is a kind of vehicle?", options:["motorbike","plate","sock"], correct:0},
  {question:"Which one needs water to grow?", options:["plant","phone","lamp"], correct:0},
  {question:"Which one is found in the desert?", options:["camel","fish","penguin"], correct:0},
  {question:"Which one has a tail?", options:["monkey","table","lamp"], correct:0},

  {question:"Which one is used to write on the board?", options:["marker","cup","knife"], correct:0},
  {question:"Which one is part of the arm?", options:["elbow","toe","hair"], correct:0},
  {question:"Which one is used at school?", options:["desk","pillow","pan"], correct:0},
  {question:"Which one is a big animal?", options:["elephant","mouse","ant"], correct:0},
  {question:"Which one is a common snack?", options:["cookies","chair","pencil"], correct:0},
  {question:"Which one is a natural resource?", options:["water","toy","cup"], correct:0},
  {question:"Which one is used for cooking rice?", options:["rice cooker","radio","box"], correct:0},
  {question:"Which one can run fast?", options:["horse","snail","turtle"], correct:0},
  {question:"Which one belongs in the bathroom?", options:["toothpaste","pencil","glass"], correct:0},
  {question:"Which one is a fruit?", options:["mango","soap","phone"], correct:0},

    {question:"Which one is used for cutting food?", options:["knife","pen","ball"], correct:0},
  {question:"Which one is a pet?", options:["cat","tiger","lion"], correct:0},
  {question:"Which one is red?", options:["strawberry","milk","paper"], correct:0},
  {question:"Which one is used in the bathroom?", options:["soap","shoe","book"], correct:0},
  {question:"Which one is a wild animal?", options:["tiger","goat","cow"], correct:0},
  {question:"Which one tastes sweet?", options:["chocolate","salt","pepper"], correct:0},
  {question:"Which one is found in the sky?", options:["cloud","desk","plate"], correct:0},
  {question:"Which one is used for travel?", options:["train","tree","cup"], correct:0},
  {question:"Which one is used by a student?", options:["notebook","fork","pillow"], correct:0},
  {question:"Which one is used to drink?", options:["cup","shoes","pencil"], correct:0},

  {question:"Which one is part of the face?", options:["nose","elbow","foot"], correct:0},
  {question:"Which one grows on bushes?", options:["berries","bikes","hats"], correct:0},
  {question:"Which one is used to open a door?", options:["key","pen","comb"], correct:0},
  {question:"Which one is used for washing clothes?", options:["washing machine","microwave","radio"], correct:0},
  {question:"Which one is a kind of drink?", options:["juice","rock","paper"], correct:0},
  {question:"Which one has stripes?", options:["zebra","sheep","goat"], correct:0},
  {question:"Which one is warm clothing?", options:["jacket","shorts","slippers"], correct:0},
  {question:"Which one is a flower?", options:["rose","plate","cup"], correct:0},
  {question:"Which one is used in the living room?", options:["sofa","ruler","box"], correct:0},
  {question:"Which one is used at school?", options:["chalk","blanket","knife"], correct:0},

  {question:"Which one is a continent?", options:["Asia","Paris","Amazon"], correct:0},
  {question:"Which one is a fruit?", options:["watermelon","battery","glass"], correct:0},
  {question:"Which one is hot?", options:["fire","ice","snow"], correct:0},
  {question:"Which one is cold?", options:["snow","tea","sun"], correct:0},
  {question:"Which one is a vegetable?", options:["carrot","cookie","bread"], correct:0},
  {question:"Which one is used for writing?", options:["pen","spoon","shoes"], correct:0},
  {question:"Which one is a baby animal?", options:["puppy","lion","tiger"], correct:0},
  {question:"Which one is used to clean teeth?", options:["toothbrush","pencil","cup"], correct:0},
  {question:"Which one is a drink?", options:["tea","rock","mirror"], correct:0},
  {question:"Which one is an insect?", options:["ant","mouse","dog"], correct:0},

  {question:"Which one is used for cooking?", options:["pan","shirt","book"], correct:0},
  {question:"Which one can fly?", options:["plane","lion","snake"], correct:0},
  {question:"Which one is a fruit?", options:["pear","hat","fan"], correct:0},
  {question:"Which one is part of the hand?", options:["finger","toe","nose"], correct:0},
  {question:"Which one is a sport?", options:["basketball","reading","sleeping"], correct:0},
  {question:"Which one is a musical instrument?", options:["guitar","plate","lamp"], correct:0},
  {question:"Which one is yellow?", options:["banana","car","water"], correct:0},
  {question:"Which one is used in the kitchen?", options:["spoon","pillow","eraser"], correct:0},
  {question:"Which one is a wild animal?", options:["lion","cow","sheep"], correct:0},
  {question:"Which one is round?", options:["ball","book","table"], correct:0},

  {question:"Which one lives underwater?", options:["fish","cat","dog"], correct:0},
  {question:"Which one is used to wash hands?", options:["soap","eraser","comb"], correct:0},
  {question:"Which one is a month?", options:["April","table","plate"], correct:0},
  {question:"Which one is used to eat soup?", options:["spoon","fork","knife"], correct:0},
  {question:"Which one is a school subject?", options:["Math","Sofa","Television"], correct:0},
  {question:"Which one has a long neck?", options:["giraffe","tiger","monkey"], correct:0},
  {question:"Which one is worn in winter?", options:["coat","T-shirt","shorts"], correct:0},
  {question:"Which one is a drink?", options:["coffee","rock","table"], correct:0},
  {question:"Which one is a fruit?", options:["kiwi","paper","shirt"], correct:0},
  {question:"Which one is used for listening?", options:["ear","eye","nose"], correct:0},

  {question:"Which one moves slowly?", options:["turtle","horse","rabbit"], correct:0},
  {question:"Which one is used to clean the floor?", options:["broom","pencil","cup"], correct:0},
  {question:"Which one is a body part?", options:["leg","bowl","bottle"], correct:0},
  {question:"Which one can jump?", options:["kangaroo","fish","snake"], correct:0},
  {question:"Which one is a fruit?", options:["peach","rock","key"], correct:0},
  {question:"Which one is used for time?", options:["watch","plate","fork"], correct:0},
  {question:"Which one is a profession?", options:["teacher","banana","door"], correct:0},
  {question:"Which one is used in art?", options:["paint","knife","phone"], correct:0},
  {question:"Which one is found at the beach?", options:["sand","book","cup"], correct:0},
  {question:"Which one is hot?", options:["tea","ice","snow"], correct:0},

  {question:"Which one is used at school?", options:["bag","comb","plate"], correct:0},
  {question:"Which one is an animal?", options:["rabbit","chair","phone"], correct:0},
  {question:"Which one is green?", options:["leaf","pen","car"], correct:0},
  {question:"Which one is used for sleeping?", options:["bed","clock","ball"], correct:0},
  {question:"Which one is a drink?", options:["juice","shirt","book"], correct:0},
  {question:"Which one is used for cooking?", options:["stove","pillow","shirt"], correct:0},
  {question:"Which one can swim?", options:["duck","cat","goat"], correct:0},
  {question:"Which one is used in the rain?", options:["umbrella","cup","fork"], correct:0},
  {question:"Which one is part of the foot?", options:["heel","nose","ear"], correct:0},
  {question:"Which one is an animal?", options:["bear","plate","fork"], correct:0},

  {question:"Which one is a fruit?", options:["papaya","bottle","soap"], correct:0},
  {question:"Which one is used for drinking?", options:["glass","knife","towel"], correct:0},
  {question:"Which one is a month?", options:["June","pencil","bag"], correct:0},
  {question:"Which one has feathers?", options:["chicken","sheep","cow"], correct:0},
  {question:"Which one is yellow?", options:["lemon","milk","paper"], correct:0},
  {question:"Which one is used to cut paper?", options:["scissors","spoon","cup"], correct:0},
  {question:"Which one is used for cooking rice?", options:["rice cooker","radio","towel"], correct:0},
  {question:"Which one has four wheels?", options:["car","dog","fish"], correct:0},
  {question:"Which one is found in the fridge?", options:["milk","shoes","pen"], correct:0},
  {question:"Which one is part of the arm?", options:["wrist","toe","hair"], correct:0},

  {question:"Which one is worn on the head?", options:["hat","shoe","sock"], correct:0},
  {question:"Which one is used for writing?", options:["marker","spoon","plate"], correct:0},
  {question:"Which one lives in water?", options:["shark","cat","wolf"], correct:0},
  {question:"Which one is used for cleaning?", options:["soap","book","pencil"], correct:0},
  {question:"Which one is food?", options:["pizza","rock","pen"], correct:0},
  {question:"Which one is fast?", options:["cheetah","snail","turtle"], correct:0},
  {question:"Which one is used for studying?", options:["book","fork","glass"], correct:0},
  {question:"Which one is a fruit?", options:["plum","soap","paper"], correct:0},
  {question:"Which one is a drink?", options:["tea","stone","sho]();
    
