window.QBANK5 = [
  {question:"Which one is used for cutting food?", options:["knife","pen","ball"], correct:0},
  {question:"Which one is a pet?", options:["cat","tiger","lion"], correct:0},
  {question:"Which one is red?", options:["strawberry","milk","paper"], correct:0},
  {question:"Which one is used in the bathroom?", options:["soap","shoe","book"], correct:0},
  {question:"Which one is a wild animal?", options:["tiger","goat","cow"], correct:0},
  {question:"Which one tastes sweet?", options:["chocolate","salt","pepper"], correct:0},
  {question:"Which one is found in the sky?", options:["cloud","desk","plate"], correct:0},
  {question:"Which one is used for travel?", options:["train","tree","cup"], correct:0},
  {question:"Which one is used by a student?", options:["notebook","fork","pillow"], correct:0},
  {question:"Which one is used to drink?", options:["cup","shoes","pencil"], correct:0},

  {question:"Which one is part of the face?", options:["nose","elbow","foot"], correct:0},
  {question:"Which one grows on bushes?", options:["berries","bikes","hats"], correct:0},
  {question:"Which one is used to open a door?", options:["key","pen","comb"], correct:0},
  {question:"Which one is used for washing clothes?", options:["washing machine","microwave","radio"], correct:0},
  {question:"Which one is a kind of drink?", options:["juice","rock","paper"], correct:0},
  {question:"Which one has stripes?", options:["zebra","sheep","goat"], correct:0},
  {question:"Which one is warm clothing?", options:["jacket","shorts","slippers"], correct:0},
  {question:"Which one is a flower?", options:["rose","plate","cup"], correct:0},
  {question:"Which one is used in the living room?", options:["sofa","ruler","box"], correct:0},
  {question:"Which one is used at school?", options:["chalk","blanket","knife"], correct:0},

  {question:"Which one is a continent?", options:["Asia","Paris","Amazon"], correct:0},
  {question:"Which one is a fruit?", options:["watermelon","battery","glass"], correct:0},
  {question:"Which one is hot?", options:["fire","ice","snow"], correct:0},
  {question:"Which one is cold?", options:["snow","tea","sun"], correct:0},
  {question:"Which one is a vegetable?", options:["carrot","cookie","bread"], correct:0},
  {question:"Which one is used for writing?", options:["pen","spoon","shoes"], correct:0},
  {question:"Which one is a baby animal?", options:["puppy","lion","tiger"], correct:0},
  {question:"Which one is used to clean teeth?", options:["toothbrush","pencil","cup"], correct:0},
  {question:"Which one is a drink?", options:["tea","rock","mirror"], correct:0},
  {question:"Which one is an insect?", options:["ant","mouse","dog"], correct:0},

  {question:"Which one is used for cooking?", options:["pan","shirt","book"], correct:0},
  {question:"Which one can fly?", options:["plane","lion","snake"], correct:0},
  {question:"Which one is a fruit?", options:["pear","hat","fan"], correct:0},
  {question:"Which one is part of the hand?", options:["finger","toe","nose"], correct:0},
  {question:"Which one is a sport?", options:["basketball","reading","sleeping"], correct:0},
  {question:"Which one is a musical instrument?", options:["guitar","plate","lamp"], correct:0},
  {question:"Which one is yellow?", options:["banana","car","water"], correct:0},
  {question:"Which one is used in the kitchen?", options:["spoon","pillow","eraser"], correct:0},
  {question:"Which one is a wild animal?", options:["lion","cow","sheep"], correct:0},
  {question:"Which one is round?", options:["ball","book","table"], correct:0},

  {question:"Which one lives underwater?", options:["fish","cat","dog"], correct:0},
  {question:"Which one is used to wash hands?", options:["soap","eraser","comb"], correct:0},
  {question:"Which one is a month?", options:["April","table","plate"], correct:0},
  {question:"Which one is used to eat soup?", options:["spoon","fork","knife"], correct:0},
  {question:"Which one is a school subject?", options:["Math","Sofa","Television"], correct:0},
  {question:"Which one has a long neck?", options:["giraffe","tiger","monkey"], correct:0},
  {question:"Which one is worn in winter?", options:["coat","T-shirt","shorts"], correct:0},
  {question:"Which one is a drink?", options:["coffee","rock","table"], correct:0},
  {question:"Which one is a fruit?", options:["kiwi","paper","shirt"], correct:0},
  {question:"Which one is used for listening?", options:["ear","eye","nose"], correct:0},

  {question:"Which one moves slowly?", options:["turtle","horse","rabbit"], correct:0},
  {question:"Which one is used to clean the floor?", options:["broom","pencil","cup"], correct:0},
  {question:"Which one is a body part?", options:["leg","bowl","bottle"], correct:0},
  {question:"Which one can jump?", options:["kangaroo","fish","snake"], correct:0},
  {question:"Which one is a fruit?", options:["peach","rock","key"], correct:0},
  {question:"Which one is used for time?", options:["watch","plate","fork"], correct:0},
  {question:"Which one is a profession?", options:["teacher","banana","door"], correct:0},
  {question:"Which one is used in art?", options:["paint","knife","phone"], correct:0},
  {question:"Which one is found at the beach?", options:["sand","book","cup"], correct:0},
  {question:"Which one is hot?", options:["tea","ice","snow"], correct:0},

  {question:"Which one is used at school?", options:["bag","comb","plate"], correct:0},
  {question:"Which one is an animal?", options:["rabbit","chair","phone"], correct:0},
  {question:"Which one is green?", options:["leaf","pen","car"], correct:0},
  {question:"Which one is used for sleeping?", options:["bed","clock","ball"], correct:0},
  {question:"Which one is a drink?", options:["juice","shirt","book"], correct:0},
  {question:"Which one is used for cooking?", options:["stove","pillow","shirt"], correct:0},
  {question:"Which one can swim?", options:["duck","cat","goat"], correct:0},
  {question:"Which one is used in the rain?", options:["umbrella","cup","fork"], correct:0},
  {question:"Which one is part of the foot?", options:["heel","nose","ear"], correct:0},
  {question:"Which one is an animal?", options:["bear","plate","fork"], correct:0},

  {question:"Which one is a fruit?", options:["papaya","bottle","soap"], correct:0},
  {question:"Which one is used for drinking?", options:["glass","knife","towel"], correct:0},
  {question:"Which one is a month?", options:["June","pencil","bag"], correct:0},
  {question:"Which one has feathers?", options:["chicken","sheep","cow"], correct:0},
  {question:"Which one is yellow?", options:["lemon","milk","paper"], correct:0},
  {question:"Which one is used to cut paper?", options:["scissors","spoon","cup"], correct:0},
  {question:"Which one is used for cooking rice?", options:["rice cooker","radio","towel"], correct:0},
  {question:"Which one has four wheels?", options:["car","dog","fish"], correct:0},
  {question:"Which one is found in the fridge?", options:["milk","shoes","pen"], correct:0},
  {question:"Which one is part of the arm?", options:["wrist","toe","hair"], correct:0},

  {question:"Which one is worn on the head?", options:["hat","shoe","sock"], correct:0},
  {question:"Which one is used for writing?", options:["marker","spoon","plate"], correct:0},
  {question:"Which one lives in water?", options:["shark","cat","wolf"], correct:0},
  {question:"Which one is used for cleaning?", options:["soap","book","pencil"], correct:0},
  {question:"Which one is food?", options:["pizza","rock","pen"], correct:0},
  {question:"Which one is fast?", options:["cheetah","snail","turtle"], correct:0},
  {question:"Which one is used for studying?", options:["book","fork","glass"], correct:0},
  {question:"Which one is a fruit?", options:["plum","soap","paper"], correct:0},
  {question:"Which one is a drink?", options:["tea","stone","sho]()
