window.QBANK2 = [
  {question:"Which one is a vegetable?", options:["carrot","car","cat"], correct:0},
  {question:"What do you use to cut paper?", options:["scissors","phone","soap"], correct:0},
  {question:"Which is a fruit?", options:["grape","chair","shoe"], correct:0},
  {question:"Which one is a farm animal?", options:["cow","bus","pen"], correct:0},
  {question:"Which one can fly?", options:["airplane","book","desk"], correct:0},
  {question:"Which one is cold?", options:["ice","fire","sun"], correct:0},
  {question:"Which one grows on trees?", options:["apple","rock","car"], correct:0},
  {question:"What do you wear on your feet?", options:["shoes","gloves","hat"], correct:0},
  {question:"Which is a body part?", options:["hand","table","door"], correct:0},
  {question:"Which one tells time?", options:["clock","pen","bottle"], correct:0},

  {question:"Which one is a color?", options:["yellow","bread","phone"], correct:0},
  {question:"Which one is a sport?", options:["tennis","book","cup"], correct:0},
  {question:"Which one is a season?", options:["winter","pencil","shirt"], correct:0},
  {question:"What do you drink in the morning?", options:["milk","car","shoe"], correct:0},
  {question:"Which one is a musical instrument?", options:["piano","apple","bus"], correct:0},
  {question:"Which word means 'begin'?", options:["start","end","stop"], correct:0},
  {question:"Which one is a farm product?", options:["egg","phone","chair"], correct:0},
  {question:"Which one is a tool?", options:["hammer","banana","dog"], correct:0},
  {question:"Which one is hot?", options:["sun","water","cake"], correct:0},
  {question:"Which one is a vehicle?", options:["train","pen","rice"], correct:0},

  {question:"Which one is an occupation?", options:["doctor","tree","river"], correct:0},
  {question:"What do you write with?", options:["pencil","plate","shoe"], correct:0},
  {question:"Which one is a planet?", options:["Earth","book","banana"], correct:0},
  {question:"Which one is a kitchen item?", options:["spoon","car","hat"], correct:0},
  {question:"Which is a natural resource?", options:["water","phone","table"], correct:0},
  {question:"Which one is delicious to eat?", options:["cake","stone","cup"], correct:0},
  {question:"Which one is a hobby?", options:["painting","river","mountain"], correct:0},
  {question:"Which one is a healthy drink?", options:["water","cola","oil"], correct:0},
  {question:"Which one is a place to buy food?", options:["market","school","station"], correct:0},
  {question:"Which one is a weather condition?", options:["rain","lamp","chair"], correct:0},

  {question:"Which one is a vehicle that moves on water?", options:["ship","bicycle","plane"], correct:0},
  {question:"Which one keeps you warm?", options:["coat","glass","pen"], correct:0},
  {question:"Which one helps you see at night?", options:["lamp","pillow","shoe"], correct:0},
  {question:"Which one do you read?", options:["book","rice","car"], correct:0},
  {question:"Which one grows vegetables?", options:["garden","school","hospital"], correct:0},
  {question:"Which one makes bread?", options:["oven","chair","car"], correct:0},
  {question:"Which one is a building for learning?", options:["school","factory","park"], correct:0},
  {question:"Which one is used to cut food?", options:["knife","shampoo","chair"], correct:0},
  {question:"Which one gives us milk?", options:["cow","dog","fish"], correct:0},
  {question:"Which one lives in a house and barks?", options:["dog","bird","fish"], correct:0},

  {question:"Which one is a useful liquid?", options:["water","stone","pencil"], correct:0},
  {question:"Which one is a holiday month in summer?", options:["July","November","February"], correct:0},
  {question:"Which one is a tool to write on a board?", options:["marker","spoon","plate"], correct:0},
  {question:"Which one tells news on TV?", options:["anchor","teacher","chef"], correct:0},
  {question:"Which one helps people cross water?", options:["bridge","mountain","tree"], correct:0},
  {question:"Which one is used to clean your teeth?", options:["toothbrush","soap","pen"], correct:0},
  {question:"Which one is a sweet food?", options:["chocolate","salt","pepper"], correct:0},
  {question:"Which one is a place to watch movies?", options:["cinema","gym","library"], correct:0},
  {question:"Which one is a mode of communication?", options:["phone","cup","shoe"], correct:0},
  {question:"Which one can you wear on your head?", options:["hat","book","table"], correct:0},

  {question:"Which one helps you hear?", options:["ear","eye","nose"], correct:0},
  {question:"Which one helps you smell?", options:["nose","hand","foot"], correct:0},
  {question:"Which one is used for cleaning?", options:["soap","pencil","banana"], correct:0},
  {question:"Which one is a type of house?", options:["apartment","car","apple"], correct:0},
  {question:"Which one is a tool for digging?", options:["shovel","fork","knife"], correct:0},
  {question:"Which one is used to call someone?", options:["phone","book","pen"], correct:0},
  {question:"Which one is part of a tree?", options:["leaf","shoe","chair"], correct:0},
  {question:"Which one is used to carry things?", options:["bag","plate","bottle"], correct:0},
  {question:"Which one is a type of weather?", options:["windy","cloudy","apple"], correct:0},
  {question:"Which one is a place to buy books?", options:["bookstore","garage","garden"], correct:0},

  {question:"Which one is a healthy food?", options:["vegetable","candy","chip"], correct:0},
  {question:"Which one is made from wood?", options:["table","glass","rice"], correct:0},
  {question:"Which one is a tool to measure time?", options:["clock","ruler","spoon"], correct:0},
  {question:"Which one is a weekend day?", options:["Saturday","Tuesday","Wednesday"], correct:0},
  {question:"Which one do farmers grow?", options:["rice","phone","shoe"], correct:0},
  {question:"Which one is in the sky at night?", options:["stars","car","tree"], correct:0},
  {question:"Which one keeps you dry in the rain?", options:["umbrella","fan","clock"], correct:0},
  {question:"Which one is used for writing on paper?", options:["pen","plate","shoe"], correct:0},
  {question:"Which one helps you taste food?", options:["tongue","nose","ear"], correct:0},
  {question:"Which one is used for playing soccer?", options:["ball","book","plate"], correct:0},

  {question:"Which one is a piece of furniture?", options:["chair","cloud","apple"], correct:0},
  {question:"Which one is used to open a door?", options:["key","phone","apple"], correct:0},
  {question:"Which one is a tool for cleaning the floor?", options:["broom","knife","fork"], correct:0},
  {question:"Which one is a cold drink?", options:["cola","soup","rice"], correct:0},
  {question:"Which one is made from cotton?", options:["shirt","stone","glass"], correct:0},
  {question:"Which one is for cutting hair?", options:["scissors","fork","spoon"], correct:0},
  {question:"Which one is a place to sleep?", options:["bed","table","chair"], correct:0},
  {question:"Which one is a food you fry?", options:["egg","water","book"], correct:0},
  {question:"Which one gives us eggs?", options:["hen","cow","fish"], correct:0},
  {question:"Which one is in the kitchen?", options:["stove","bed","car"], correct:0},

  {question:"Which one is used to write lessons?", options:["notebook","shoe","phone"], correct:0},
  {question:"Which one helps you walk on snow?", options:["boots","sandals","socks"], correct:0},
  {question:"Which one is used to heat food?", options:["microwave","pen","bottle"], correct:0},
  {question:"Which one is a place for medicine?", options:["clinic","bar","park"], correct:0},
  {question:"Which one is a public transport?", options:["taxi","sofa","lamp"], correct:0},
  {question:"Which one is a musical group member?", options:["singer","teacher","chef"], correct:0},
  {question:"Which one is part of the body that sees?", options:["eye","ear","hand"], correct:0},
  {question:"Which is used for cutting paper?", options:["scissors","fork","knife"], correct:0},
  {question:"Which one grows in the garden?", options:["flower","car","phone"], correct:0},
  {question:"Which one is a quiet place to read?", options:["library","stadium","market"], correct:0}
];
