window.QBANK1 = [
  {question:"What is the opposite of 'big'?", options:["small", "slow", "cold"], correct:0},
  {question:"Which one is a fruit?", options:["apple","car","dog"], correct:0},
  {question:"Which word means 'teacher'?", options:["teacher","cat","bus"], correct:0},
  {question:"What color is the sky?", options:["blue","red","black"], correct:0},
  {question:"Which one is a pet?", options:["dog","car","bus"], correct:0},
  {question:"What do you drink?", options:["water","shoe","pencil"], correct:0},
  {question:"Which one is a vehicle?", options:["bike","banana","cat"], correct:0},
  {question:"Which word means 'fast'?", options:["quick","slow","cold"], correct:0},
  {question:"What is the opposite of 'hot'?", options:["cold","warm","tiny"], correct:0},
  {question:"Which one is a sport?", options:["football","apple","pencil"], correct:0},

  {question:"Which one is a fruit?", options:["banana","train","dog"], correct:0},
  {question:"What do you use to write?", options:["pen","orange","milk"], correct:0},
  {question:"Which animal can fly?", options:["bird","dog","fish"], correct:0},
  {question:"Which one is food?", options:["rice","bike","shirt"], correct:0},
  {question:"Which one is a job?", options:["teacher","milk","banana"], correct:0},
  {question:"Which word means 'happy'?", options:["glad","sad","angry"], correct:0},
  {question:"Which one is a drink?", options:["juice","cat","bus"], correct:0},
  {question:"What is the opposite of 'slow'?", options:["fast","small","red"], correct:0},
  {question:"Which is a season?", options:["summer","apple","car"], correct:0},
  {question:"Which one is a place?", options:["school","banana","dog"], correct:0},

  {question:"Which one is a day of the week?", options:["Monday","Banana","Water"], correct:0},
  {question:"Which one is a month?", options:["January","Apple","Milk"], correct:0},
  {question:"Which one is a fruit?", options:["grape","bus","shoe"], correct:0},
  {question:"Which word means 'run'?", options:["run","sleep","sit"], correct:0},
  {question:"Which animal lives in water?", options:["fish","cat","bird"], correct:0},
  {question:"Which one is a building?", options:["library","juice","dog"], correct:0},
  {question:"Which one is a drink?", options:["milk","book","pencil"], correct:0},
  {question:"What is the opposite of 'young'?", options:["old","fast","hot"], correct:0},
  {question:"Which is a school subject?", options:["math","bread","bike"], correct:0},
  {question:"Which one is a vehicle?", options:["bus","apple","dog"], correct:0},

  {question:"Which one is a fruit?", options:["orange","car","shoe"], correct:0},
  {question:"Which word means 'sleep'?", options:["sleep","run","talk"], correct:0},
  {question:"Which one is a job?", options:["student","milk","shirt"], correct:0},
  {question:"Which animal is small?", options:["cat","train","bus"], correct:0},
  {question:"Which one is food?", options:["bread","bike","stone"], correct:0},
  {question:"Which is a feeling?", options:["sad","table","bus"], correct:0},
  {question:"Which word means 'eat'?", options:["eat","run","jump"], correct:0},
  {question:"Which one is a drink?", options:["water","shoe","banana"], correct:0},
  {question:"Which one is a color?", options:["red","bus","dog"], correct:0},
  {question:"What is the opposite of 'dark'?", options:["light","cold","big"], correct:0},

  {question:"Which one is a fruit?", options:["pineapple","pen","cup"], correct:0},
  {question:"Which one is an animal?", options:["dog","car","shirt"], correct:0},
  {question:"Which word means 'write'?", options:["write","jump","swim"], correct:0},
  {question:"Which one is a place?", options:["market","banana","shoe"], correct:0},
  {question:"Which one is food?", options:["noodle","bike","bag"], correct:0},
  {question:"Which word means 'speak'?", options:["speak","run","sleep"], correct:0},
  {question:"Which one is a drink?", options:["juice","bus","cat"], correct:0},
  {question:"Which animal can swim?", options:["fish","cat","bird"], correct:0},
  {question:"Which one is a job?", options:["teacher","water","shirt"], correct:0},
  {question:"Which is a day of the week?", options:["Friday","Orange","Milk"], correct:0},

  {question:"Which is a month?", options:["May","Cat","Bike"], correct:0},
  {question:"Which one is a fruit?", options:["apple","pen","car"], correct:0},
  {question:"Which word means 'read'?", options:["read","eat","jump"], correct:0},
  {question:"Which one is an emotion?", options:["angry","bus","stone"], correct:0},
  {question:"Which one is food?", options:["rice","train","shirt"], correct:0},
  {question:"Which one is a drink?", options:["milk","dog","box"], correct:0},
  {question:"Which is a vehicle?", options:["car","bread","apple"], correct:0},
  {question:"Which one is a place?", options:["school","banana","milk"], correct:0},
  {question:"Which animal is big?", options:["elephant","ant","fish"], correct:0},
  {question:"Which is a color?", options:["blue","cat","bus"], correct:0},

  {question:"Which one is a fruit?", options:["banana","door","shoe"], correct:0},
  {question:"Which one is a job?", options:["student","juice","table"], correct:0},
  {question:"Which word means 'jump'?", options:["jump","read","drink"], correct:0},
  {question:"Which one is food?", options:["bread","car","glass"], correct:0},
  {question:"Which one is a drink?", options:["water","pen","hat"], correct:0},
  {question:"Which is a feeling?", options:["happy","bike","train"], correct:0},
  {question:"Which is a day?", options:["Sunday","Banana","Milk"], correct:0},
  {question:"Which one is a vehicle?", options:["bike","cat","pencil"], correct:0},
  {question:"Which one is a month?", options:["June","Shoe","Dog"], correct:0},
  {question:"Which one is a fruit?", options:["grape","bus","bag"], correct:0},

  {question:"Which one is a place?", options:["library","juice","pencil"], correct:0},
  {question:"Which one is an animal?", options:["bird","car","milk"], correct:0},
  {question:"Which one is food?", options:["noodle","bag","shoe"], correct:0},
  {question:"Which is a subject?", options:["English","Dog","Car"], correct:0},
  {question:"Which one is a drink?", options:["juice","stone","bus"], correct:0},
  {question:"Which one is a job?", options:["teacher","apple","water"], correct:0},
  {question:"Which word means 'walk'?", options:["walk","jump","swim"], correct:0},
  {question:"Which one is a color?", options:["green","fish","bus"], correct:0},
  {question:"Which animal is small?", options:["ant","bus","plane"], correct:0},
  {question:"Which one is food?", options:["rice","car","shoe"], correct:0}
];
