window.QBANK3 = [
  {question:"Which one is a wild animal?", options:["tiger","cow","chicken"], correct:0},
  {question:"Which one is used to light a dark room?", options:["lamp","cup","fork"], correct:0},
  {question:"Which one is a fruit you peel?", options:["banana","bread","car"], correct:0},
  {question:"Which one is part of the body?", options:["leg","cup","tree"], correct:0},
  {question:"Which one is used for washing hands?", options:["soap","pencil","towel"], correct:0},
  {question:"Which one protects you from rain?", options:["umbrella","plate","book"], correct:0},
  {question:"Which one is a type of drink?", options:["juice","shoe","chalk"], correct:0},
  {question:"Which one is a school subject?", options:["math","plate","chair"], correct:0},
  {question:"Which one is made of paper?", options:["newspaper","key","water"], correct:0},
  {question:"Which one is a small animal?", options:["mouse","bus","tree"], correct:0},

  {question:"Which one is used to cook soup?", options:["pot","plate","glass"], correct:0},
  {question:"Which one is a place to swim?", options:["pool","school","cinema"], correct:0},
  {question:"Which one is used to see far objects?", options:["binoculars","fork","spoon"], correct:0},
  {question:"Which one is a part of the face?", options:["nose","hand","foot"], correct:0},
  {question:"Which one is a natural place?", options:["forest","building","hotel"], correct:0},
  {question:"Which one can fly in the sky?", options:["bird","lion","tiger"], correct:0},
  {question:"Which one is a type of weather?", options:["sunny","chair","soap"], correct:0},
  {question:"Which one is used for music?", options:["guitar","brush","ruler"], correct:0},
  {question:"Which one is a communication tool?", options:["computer","cup","box"], correct:0},
  {question:"Which one is used to carry students?", options:["school bus","motorbike","plate"], correct:0},

  {question:"Which one is a plant?", options:["flower","dog","car"], correct:0},
  {question:"Which one is used for drinking?", options:["cup","shoe","pen"], correct:0},
  {question:"Which is a type of building?", options:["hospital","banana","pencil"], correct:0},
  {question:"Which one is used to color pictures?", options:["crayons","knife","spoon"], correct:0},
  {question:"Which one has wheels?", options:["bicycle","egg","chair"], correct:0},
  {question:"Which one is a pet?", options:["cat","tiger","cow"], correct:0},
  {question:"Which one is a warm season?", options:["summer","winter","autumn"], correct:0},
  {question:"Which one is used to clean the board?", options:["eraser","fork","glass"], correct:0},
  {question:"Which one is a time of day?", options:["morning","table","car"], correct:0},
  {question:"Which one is for holding plants?", options:["flower pot","fridge","box"], correct:0},

  {question:"Which one is a body joint?", options:["knee","ear","nose"], correct:0},
  {question:"Which one is a tall animal?", options:["giraffe","cat","pig"], correct:0},
  {question:"Which one is used for shopping?", options:["cart","bed","pen"], correct:0},
  {question:"Which one is for boiling water?", options:["kettle","plate","pencil"], correct:0},
  {question:"Which one is sweet?", options:["honey","salt","pepper"], correct:0},
  {question:"Which one protects your eyes?", options:["sunglasses","gloves","boots"], correct:0},
  {question:"Which one is a sea animal?", options:["fish","cow","bird"], correct:0},
  {question:"Which one is a tree part?", options:["branch","shoe","phone"], correct:0},
  {question:"Which one belongs in the bathroom?", options:["shampoo","fork","clock"], correct:0},
  {question:"Which one helps you go upstairs?", options:["stairs","window","desk"], correct:0},

  {question:"Which one is a big body of water?", options:["ocean","cup","bowl"], correct:0},
  {question:"Which one shows temperature?", options:["thermometer","ruler","marker"], correct:0},
  {question:"Which one can you play?", options:["game","rice","car"], correct:0},
  {question:"Which one is a container?", options:["bottle","pencil","shoe"], correct:0},
  {question:"Which one is a mode of travel?", options:["train","cup","hat"], correct:0},
  {question:"Which one is eaten at breakfast?", options:["bread","pencil","soap"], correct:0},
  {question:"Which one is a dessert?", options:["ice cream","water","salt"], correct:0},
  {question:"Which one is a part of the hand?", options:["finger","toe","nose"], correct:0},
  {question:"Which one has pages?", options:["book","shoe","knife"], correct:0},
  {question:"Which one is used for measuring length?", options:["ruler","bowl","brush"], correct:0},

  {question:"Which one is a small insect?", options:["ant","cow","lion"], correct:0},
  {question:"Which one is a home appliance?", options:["fridge","car","tree"], correct:0},
  {question:"Which one is noisy?", options:["drum","pillow","paper"], correct:0},
  {question:"Which one lives in the water?", options:["fish","cat","dog"], correct:0},
  {question:"Which one is eaten as a snack?", options:["chips","soap","pen"], correct:0},
  {question:"Which one is a round object?", options:["ball","book","cupboard"], correct:0},
  {question:"Which one helps you breathe?", options:["lungs","hand","eye"], correct:0},
  {question:"Which one is a thing you wear?", options:["shirt","knife","pencil"], correct:0},
  {question:"Which one is used for cutting?", options:["knife","spoon","cup"], correct:0},
  {question:"Which one is a type of job?", options:["teacher","blanket","window"], correct:0},

  {question:"Which one is used to eat soup?", options:["spoon","knife","stick"], correct:0},
  {question:"Which one has four wheels?", options:["car","dog","chair"], correct:0},
  {question:"Which one is used at school?", options:["chalk","knife","bowl"], correct:0},
  {question:"Which one is a piece of clothing?", options:["jacket","leaf","stone"], correct:0},
  {question:"Which one is part of the mouth?", options:["teeth","hair","ear"], correct:0},
  {question:"Which one is used for timekeeping?", options:["watch","pen","plate"], correct:0},
  {question:"Which one is found in the sky?", options:["cloud","desk","cup"], correct:0},
  {question:"Which one is a public place?", options:["library","pan","shoe"], correct:0},
  {question:"Which one is used for cleaning floors?", options:["mop","knife","glass"], correct:0},
  {question:"Which one is something you drink?", options:["water","rock","key"], correct:0},

  {question:"Which one is a house pet?", options:["dog","lion","wolf"], correct:0},
  {question:"Which one is a container for water?", options:["bucket","plate","shoe"], correct:0},
  {question:"Which one grows in orchards?", options:["fruit","iron","paper"], correct:0},
  {question:"Which one is a cold place?", options:["North Pole","desert","forest"], correct:0},
  {question:"Which one tells directions?", options:["compass","broom","glass"], correct:0},
  {question:"Which one is soft?", options:["pillow","rock","metal"], correct:0},
  {question:"Which one is worn on the hands?", options:["gloves","hat","scarf"], correct:0},
  {question:"Which one is a fast animal?", options:["cheetah","turtle","sheep"], correct:0},
  {question:"Which one is a body part?", options:["shoulder","bottle","cap"], correct:0},
  {question:"Which one is used for cooking?", options:["pan","shoe","pen"], correct:0}
];

