window.QBANK4 = [
  {question:"Which one is a farm animal?", options:["cow","lion","tiger"], correct:0},
  {question:"Which one is used for writing?", options:["pen","spoon","plate"], correct:0},
  {question:"Which one grows on trees?", options:["apple","car","shoe"], correct:0},
  {question:"Which one can fly?", options:["bird","elephant","dog"], correct:0},
  {question:"Which one is for drinking?", options:["glass","shoe","key"], correct:0},
  {question:"Which one is a kind of weather?", options:["rainy","knife","fork"], correct:0},
  {question:"Which one is a fruit?", options:["orange","hat","rock"], correct:0},
  {question:"Which one is part of the leg?", options:["knee","hair","nose"], correct:0},
  {question:"Which one is hot?", options:["sun","ice","snow"], correct:0},
  {question:"Which one is used for cutting paper?", options:["scissors","candle","cup"], correct:0},

  {question:"Which one is a vehicle?", options:["bus","banana","cat"], correct:0},
  {question:"Which one is cold?", options:["ice","fire","sun"], correct:0},
  {question:"Which one is eaten?", options:["food","pencil","shirt"], correct:0},
  {question:"Which one lives in the jungle?", options:["monkey","cow","goat"], correct:0},
  {question:"Which one is used in class?", options:["notebook","pillow","blanket"], correct:0},
  {question:"Which one is a color?", options:["blue","cup","fish"], correct:0},
  {question:"Which one has leaves?", options:["tree","shoe","cupboard"], correct:0},
  {question:"Which one is used to wash hair?", options:["shampoo","knife","glass"], correct:0},
  {question:"Which one is a sport?", options:["football","cooking","sleeping"], correct:0},
  {question:"Which one is part of the head?", options:["hair","foot","hand"], correct:0},

  {question:"Which one is a meal?", options:["breakfast","pencil","door"], correct:0},
  {question:"Which one is used to draw?", options:["pencil","fork","stick"], correct:0},
  {question:"Which one grows in the garden?", options:["flower","table","hat"], correct:0},
  {question:"Which one is a body part?", options:["neck","plate","bottle"], correct:0},
  {question:"Which one can swim?", options:["fish","cat","tiger"], correct:0},
  {question:"Which one is a holiday month?", options:["December","plate","box"], correct:0},
  {question:"Which one is a natural place?", options:["beach","pencil","bag"], correct:0},
  {question:"Which one is made of metal?", options:["key","banana","bread"], correct:0},
  {question:"Which one is a school item?", options:["ruler","pan","shoe"], correct:0},
  {question:"Which one is used for eating?", options:["fork","ball","ruler"], correct:0},

  {question:"Which one is a drink?", options:["milk","rock","paper"], correct:0},
  {question:"Which one is used at night to sleep?", options:["bed","bus","book"], correct:0},
  {question:"Which one can jump?", options:["frog","fish","chair"], correct:0},
  {question:"Which one is a room in the house?", options:["kitchen","flower","bottle"], correct:0},
  {question:"Which one is worn on the feet?", options:["shoes","hat","gloves"], correct:0},
  {question:"Which one is a kind of animal?", options:["horse","pen","cup"], correct:0},
  {question:"Which one is a type of fruit?", options:["grape","clock","water"], correct:0},
  {question:"Which one is used for music?", options:["piano","plate","bag"], correct:0},
  {question:"Which one is round?", options:["circle","box","paper"], correct:0},
  {question:"Which one grows in the sea?", options:["seaweed","lion","pig"], correct:0},

  {question:"Which one has wheels?", options:["car","cat","tree"], correct:0},
  {question:"Which one is used to sweep the floor?", options:["broom","knife","spoon"], correct:0},
  {question:"Which one is a kind of job?", options:["doctor","cup","milk"], correct:0},
  {question:"Which one is sweet?", options:["cake","salt","pepper"], correct:0},
  {question:"Which one is used to keep food cold?", options:["fridge","table","mirror"], correct:0},
  {question:"Which one has feathers?", options:["bird","dog","fish"], correct:0},
  {question:"Which one produces honey?", options:["bee","cow","duck"], correct:0},
  {question:"Which one is used for drawing?", options:["crayon","cup","fork"], correct:0},
  {question:"Which one is a family member?", options:["mother","glass","pan"], correct:0},
  {question:"Which one tells time?", options:["clock","pen","spoon"], correct:0},

  {question:"Which one is used to paint?", options:["brush","bottle","spoon"], correct:0},
  {question:"Which one can float?", options:["boat","rock","chair"], correct:0},
  {question:"Which one is a school subject?", options:["science","blanket","plate"], correct:0},
  {question:"Which one flies in the sky?", options:["plane","pig","dog"], correct:0},
  {question:"Which one is used for storing books?", options:["bookshelf","pillow","glass"], correct:0},
  {question:"Which one is a common drink?", options:["water","stone","leaf"], correct:0},
  {question:"Which one grows in fields?", options:["rice","car","cup"], correct:0},
  {question:"Which one is used for gardening?", options:["shovel","bowl","pen"], correct:0},
  {question:"Which one shines at night?", options:["moon","cup","chair"], correct:0},
  {question:"Which one is used in winter?", options:["coat","plate","comb"], correct:0},

  {question:"Which one is an electronic device?", options:["phone","ball","pencil"], correct:0},
  {question:"Which one is used in the kitchen?", options:["pan","book","shoe"], correct:0},
  {question:"Which one can bark?", options:["dog","cat","rabbit"], correct:0},
  {question:"Which one is spicy?", options:["chili","sugar","milk"], correct:0},
  {question:"Which one is a bedroom item?", options:["pillow","car","tree"], correct:0},
  {question:"Which one grows on a farm?", options:["corn","radio","plate"], correct:0},
  {question:"Which one is a kind of vehicle?", options:["motorbike","plate","sock"], correct:0},
  {question:"Which one needs water to grow?", options:["plant","phone","lamp"], correct:0},
  {question:"Which one is found in the desert?", options:["camel","fish","penguin"], correct:0},
  {question:"Which one has a tail?", options:["monkey","table","lamp"], correct:0},

  {question:"Which one is used to write on the board?", options:["marker","cup","knife"], correct:0},
  {question:"Which one is part of the arm?", options:["elbow","toe","hair"], correct:0},
  {question:"Which one is used at school?", options:["desk","pillow","pan"], correct:0},
  {question:"Which one is a big animal?", options:["elephant","mouse","ant"], correct:0},
  {question:"Which one is a common snack?", options:["cookies","chair","pencil"], correct:0},
  {question:"Which one is a natural resource?", options:["water","toy","cup"], correct:0},
  {question:"Which one is used for cooking rice?", options:["rice cooker","radio","box"], correct:0},
  {question:"Which one can run fast?", options:["horse","snail","turtle"], correct:0},
  {question:"Which one belongs in the bathroom?", options:["toothpaste","pencil","glass"], correct:0},
  {question:"Which one is a fruit?", options:["mango","soap","phone"], correct:0}
];
